### ISSUE TITLE
Package body variables and global's - Peeking

### ISSUE THREAD

**Issue by MadeManMax** [zabel-xyz/plsql-language#37]
Package variable

In case of package body variables and global's  are also not presented.
Issue/enhancement related to #8 
![image](https://user-images.githubusercontent.com/8720905/38458774-5637ddd2-3aa2-11e8-830d-a56c2fd31c27.png)

```sql
create or replace package body
MyPackage2
as

  myConst constant char(2) := '10';
  myGlobalVar number := 10;

-- Forward declaration --

  procedure pForwardDeclarations();
------------------------------------------------------
  function get_myValue(param1 in varchar2)
    return varchar2
  is
  begin
    if 1 =0 then
        null;
    end if;
    return param1 || ' TEST';
  end get_myValue;

  procedure set_myValue(param1 in varchar2)
  is
  begin
    MyPackage2.myCall('test');
    pCallInternal('test2');
    -- some other code to execute
    return;
  end set_myValue;

  procedure myCall(param1 in varchar2
                  ,param2 in varchar2)
  is
  begin
    -- some code to execute
    return;
  end myCall;

  procedure myCall(param1 in varchar2
                  ,param2 in number)
  is
  begin
    -- some code to execute
    return;
  end myCall;

procedure myCall(param1 in varchar2)
  is
  begin
    -- some code to execute
    return;
  end myCall;


  procedure pCallInternal(param1 in varchar2)
  is
    xyz MyPackage.txyz_myType;
    abc ttxyz_myType;
  begin
    -- some code to execute
    MyPackage2.myCall('Test');
    MyFunc('Test');
    MyProc('Test');
    schema.MyProc('Test');

    if x = schema.MyPackage2.myConst
    if y = myGlobalVar

    -- use of Forward declaration --
    pForwardDeclarations;
    -- use of Forward declaration --

    return;
  end pCallInternal;
------------------------------------------------------
    -- Definition --
procedure pForwardDeclarations()
as
begin
  null;
end pForwardDeclarations;
-------------------------------------------------
end MyPackage2;
```

Best regards
Mateusz

**Comment by zabel-xyz** [comment]
Version 1.3.0 improve regexp parser and should fix this issue..

**Comment by MadeManMax** [comment]
Hi,
It works better but it still gets wrong list of variables
![obraz](https://user-images.githubusercontent.com/8720905/40293512-9049e7b2-5cd1-11e8-909b-ad6fa9bce73c.png)

```sql
create or replace package body
MyPackage2
as

  myConst constant char(2) := '10';
  myGlobalVar number := 10;

-- Forward declaration --

  procedure pForwardDeclarations();
------------------------------------------------------
  function get_myValue(param1 in varchar2)
    return varchar2
  is
  begin
    if 1 =0 then
        null;
    end if;
    return param1 || ' TEST';
  end get_myValue;

  procedure set_myValue(param1 in varchar2)
  is
  begin
    MyPackage2.myCall('test');
    pCallInternal('test2');
    -- some other code to execute
    return;
  end set_myValue;

  procedure myCall(param1 in varchar2
                  ,param2 in varchar2)
  is
  begin
    -- some code to execute
    return;
  end myCall;

  procedure myCall(param1 in varchar2
                  ,param2 in number)
  is
  begin
    -- some code to execute
    return;
  end myCall;

procedure myCall(param1 in varchar2)
  is
  begin
    -- some code to execute
    return;
  end myCall;


  procedure pCallInternal(param1 in varchar2)
  is
    xyz MyPackage.txyz_myType;
    abc ttxyz_myType;
  begin
    -- some code to execute
    MyPackage2.myCall('Test');
    MyFunc('Test');
    MyProc('Test');
    schema.MyProc('Test');

    if x = schema.MyPackage2.myConst
    if y = myGlobalVar

    -- use of Forward declaration --
    pForwardDeclarations;
    -- use of Forward declaration --

    return;
  end pCallInternal;
------------------------------------------------------
    -- Definition --
procedure pForwardDeclarations()
as
  x VARCHAR2;
begin
  x := CASE WHEN pi_CPartyId         = ci_Null THEN NULL ELSE pi_CPartyId         END;
  x := CASE WHEN pi_CPartyId         = ci_Null THEN NULL ELSE pi_CPartyId         END;
  x := CASE WHEN pi_CPartyId         = ci_Null THEN NULL ELSE pi_CPartyId         END;
  null;
end pForwardDeclarations;
-------------------------------------------------
end MyPackage2;
```

There are also situations when local variables or even return, select, else ore elsif is presented as variables.
I've yet to prepare test package for this cause I can't give you my code and I'm not sure what cause it.

**Comment by zabel-xyz** [comment]
Thank you for your tests !
There is a bug with case...end; I'll fix it.

Variables are complexe to parse, because there is no explicit keyword.
So if you have some other examples to improve parser detection, don't hesitate.
Thank you

**Comment by MadeManMax** [comment]
Hi @zabel-xyz ,
I confirm. The Case end is not showing.
Thank you
